"""initial

Revision ID: 0001
Revises:
Create Date: 2026-08-26 14:27:01.644770
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("normalized_name", sa.String(length=500), nullable=False),
        sa.Column("primary_category", sa.String(length=300), nullable=True),
        sa.Column("city", sa.String(length=200), nullable=False),
        sa.Column("address", sa.String(length=1000), nullable=True),
        sa.Column("normalized_address", sa.String(length=1000), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("canonical_website", sa.String(length=2000), nullable=True),
        sa.Column("registrable_domain", sa.String(length=300), nullable=True),
        sa.Column("rating", sa.Float(), nullable=True),
        sa.Column("reviews_count", sa.Integer(), nullable=True),
        sa.Column(
            "website_status",
            sa.Enum(
                "NO_WEBSITE",
                "ONLINE",
                "DEAD",
                "TIMEOUT",
                "PARKED",
                "PLACEHOLDER",
                "ERROR",
                name="website_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "website_type",
            sa.Enum("BUSINESS_CARD", "NORMAL", name="website_type", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "cms",
            sa.Enum(
                "TILDA",
                "WIX",
                "WORDPRESS",
                "WEBFLOW",
                "BITRIX",
                "NETHOUSE",
                "FLEXBE",
                "CREATIUM",
                "LPMOTOR",
                "CUSTOM_OR_UNKNOWN",
                name="cms",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("cms_confidence", sa.Float(), nullable=False),
        sa.Column("https_enabled", sa.Boolean(), nullable=False),
        sa.Column("site_opportunity_score", sa.Integer(), nullable=False),
        sa.Column("contactability_score", sa.Integer(), nullable=False),
        sa.Column("lead_reasons", sa.JSON(), nullable=False),
        sa.Column("contacts_found", sa.Boolean(), nullable=False),
        sa.Column("contact_count", sa.Integer(), nullable=False),
        sa.Column(
            "preferred_contact_type",
            sa.Enum(
                "PHONE",
                "EMAIL",
                "WEBSITE",
                "TELEGRAM",
                "WHATSAPP",
                "VK",
                "INSTAGRAM",
                "OTHER",
                name="preferred_contact_type",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("preferred_contact_value", sa.String(length=1000), nullable=True),
        sa.Column(
            "lead_state",
            sa.Enum(
                "QUALIFIED", "BELOW_THRESHOLD", "NO_CONTACTS", name="lead_state", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("discovered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
    )
    op.create_index(op.f("ix_companies_city"), "companies", ["city"], unique=False)
    op.create_index(
        "ix_companies_city_score", "companies", ["city", "site_opportunity_score"], unique=False
    )
    op.create_index(op.f("ix_companies_cms"), "companies", ["cms"], unique=False)
    op.create_index(
        op.f("ix_companies_contacts_found"), "companies", ["contacts_found"], unique=False
    )
    op.create_index(op.f("ix_companies_lead_state"), "companies", ["lead_state"], unique=False)
    op.create_index(
        "ix_companies_name_address",
        "companies",
        ["normalized_name", "normalized_address"],
        unique=False,
    )
    op.create_index(
        op.f("ix_companies_normalized_address"), "companies", ["normalized_address"], unique=False
    )
    op.create_index(
        op.f("ix_companies_normalized_name"), "companies", ["normalized_name"], unique=False
    )
    op.create_index(
        op.f("ix_companies_primary_category"), "companies", ["primary_category"], unique=False
    )
    op.create_index(
        op.f("ix_companies_registrable_domain"), "companies", ["registrable_domain"], unique=False
    )
    op.create_index(
        op.f("ix_companies_site_opportunity_score"),
        "companies",
        ["site_opportunity_score"],
        unique=False,
    )
    op.create_index(
        op.f("ix_companies_website_status"), "companies", ["website_status"], unique=False
    )
    op.create_table(
        "search_jobs",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("city", sa.String(length=200), nullable=False),
        sa.Column("query", sa.String(length=300), nullable=False),
        sa.Column("min_rating", sa.Float(), nullable=True),
        sa.Column("min_reviews", sa.Integer(), nullable=True),
        sa.Column("max_results", sa.Integer(), nullable=False),
        sa.Column("requested_sources", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "COMPLETED_WITH_ERRORS",
                "FAILED",
                name="job_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "stage",
            sa.Enum(
                "PENDING",
                "COLLECTING",
                "DEDUPLICATING",
                "ANALYZING_WEBSITES",
                "SCORING",
                "EXPORTING",
                "FINISHED",
                name="job_stage",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("found_count", sa.Integer(), nullable=False),
        sa.Column("filtered_out_count", sa.Integer(), nullable=False),
        sa.Column("unique_count", sa.Integer(), nullable=False),
        sa.Column("analyzed_count", sa.Integer(), nullable=False),
        sa.Column("lead_count", sa.Integer(), nullable=False),
        sa.Column("contactable_lead_count", sa.Integer(), nullable=False),
        sa.Column("exported_count", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("errors", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_jobs")),
    )
    op.create_index(op.f("ix_search_jobs_status"), "search_jobs", ["status"], unique=False)
    op.create_table(
        "sheet_exports",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("spreadsheet_id", sa.String(length=500), nullable=False),
        sa.Column("worksheet_name", sa.String(length=300), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.BigInteger(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("exported_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sheet_exports")),
        sa.UniqueConstraint(
            "spreadsheet_id",
            "worksheet_name",
            "entity_type",
            "entity_id",
            name=op.f("uq_sheet_exports_spreadsheet_id"),
        ),
    )
    op.create_table(
        "company_contacts",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "company_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "type",
            sa.Enum(
                "PHONE",
                "EMAIL",
                "WEBSITE",
                "TELEGRAM",
                "WHATSAPP",
                "VK",
                "INSTAGRAM",
                "OTHER",
                name="contact_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("value", sa.String(length=1000), nullable=False),
        sa.Column("normalized_value", sa.String(length=1000), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_company_contacts_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company_contacts")),
        sa.UniqueConstraint(
            "company_id", "type", "normalized_value", name=op.f("uq_company_contacts_company_id")
        ),
    )
    op.create_index(
        op.f("ix_company_contacts_company_id"), "company_contacts", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_company_contacts_normalized_value"),
        "company_contacts",
        ["normalized_value"],
        unique=False,
    )
    op.create_index(op.f("ix_company_contacts_type"), "company_contacts", ["type"], unique=False)
    op.create_table(
        "company_sources",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "company_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "source",
            sa.Enum("google", "2gis", "yandex", name="company_source_name", native_enum=False),
            nullable=False,
        ),
        sa.Column("source_id", sa.String(length=300), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("categories", sa.JSON(), nullable=False),
        sa.Column("address", sa.String(length=1000), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("rating", sa.Float(), nullable=True),
        sa.Column("reviews_count", sa.Integer(), nullable=True),
        sa.Column("working_hours", sa.JSON(), nullable=True),
        sa.Column(
            "contacts_access",
            sa.Enum("FULL", "LIMITED", name="contacts_access", native_enum=False),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_company_sources_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company_sources")),
        sa.UniqueConstraint("source", "source_id", name=op.f("uq_company_sources_source")),
    )
    op.create_index(
        op.f("ix_company_sources_company_id"), "company_sources", ["company_id"], unique=False
    )
    op.create_table(
        "job_outbox",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "search_job_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.String(length=1000), nullable=True),
        sa.ForeignKeyConstraint(
            ["search_job_id"],
            ["search_jobs.id"],
            name=op.f("fk_job_outbox_search_job_id_search_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_outbox")),
    )
    op.create_index(
        op.f("ix_job_outbox_published_at"), "job_outbox", ["published_at"], unique=False
    )
    op.create_index(
        op.f("ix_job_outbox_search_job_id"), "job_outbox", ["search_job_id"], unique=True
    )
    op.create_table(
        "search_job_companies",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "search_job_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "company_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "processing_stage",
            sa.Enum(
                "PENDING",
                "COLLECTING",
                "DEDUPLICATING",
                "ANALYZING_WEBSITES",
                "SCORING",
                "EXPORTING",
                "FINISHED",
                name="company_processing_stage",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "first_source",
            sa.Enum("google", "2gis", "yandex", name="first_discovery_source", native_enum=False),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_search_job_companies_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["search_job_id"],
            ["search_jobs.id"],
            name=op.f("fk_search_job_companies_search_job_id_search_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_job_companies")),
        sa.UniqueConstraint(
            "search_job_id", "company_id", name=op.f("uq_search_job_companies_search_job_id")
        ),
    )
    op.create_index(
        op.f("ix_search_job_companies_company_id"),
        "search_job_companies",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_search_job_companies_search_job_id"),
        "search_job_companies",
        ["search_job_id"],
        unique=False,
    )
    op.create_table(
        "search_job_sources",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "search_job_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "source",
            sa.Enum("google", "2gis", "yandex", name="source_name", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "COMPLETED_WITH_ERRORS",
                "FAILED",
                name="source_job_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("next_cursor", sa.Text(), nullable=True),
        sa.Column("exhausted", sa.Boolean(), nullable=False),
        sa.Column("found_count", sa.Integer(), nullable=False),
        sa.Column("accepted_count", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.String(length=1000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["search_job_id"],
            ["search_jobs.id"],
            name=op.f("fk_search_job_sources_search_job_id_search_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_job_sources")),
        sa.UniqueConstraint(
            "search_job_id", "source", name=op.f("uq_search_job_sources_search_job_id")
        ),
    )
    op.create_index(
        op.f("ix_search_job_sources_search_job_id"),
        "search_job_sources",
        ["search_job_id"],
        unique=False,
    )
    op.create_table(
        "website_checks",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "company_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("requested_url", sa.String(length=2000), nullable=True),
        sa.Column("final_url", sa.String(length=2000), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "NO_WEBSITE",
                "ONLINE",
                "DEAD",
                "TIMEOUT",
                "PARKED",
                "PLACEHOLDER",
                "ERROR",
                name="check_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("https_enabled", sa.Boolean(), nullable=False),
        sa.Column("redirect_count", sa.Integer(), nullable=False),
        sa.Column("response_time_ms", sa.Integer(), nullable=True),
        sa.Column("content_type", sa.String(length=300), nullable=True),
        sa.Column(
            "cms",
            sa.Enum(
                "TILDA",
                "WIX",
                "WORDPRESS",
                "WEBFLOW",
                "BITRIX",
                "NETHOUSE",
                "FLEXBE",
                "CREATIUM",
                "LPMOTOR",
                "CUSTOM_OR_UNKNOWN",
                name="check_cms",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("cms_confidence", sa.Float(), nullable=False),
        sa.Column(
            "website_type",
            sa.Enum("BUSINESS_CARD", "NORMAL", name="check_website_type", native_enum=False),
            nullable=False,
        ),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_website_checks_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_website_checks")),
    )
    op.create_index(
        op.f("ix_website_checks_checked_at"), "website_checks", ["checked_at"], unique=False
    )
    op.create_index(
        op.f("ix_website_checks_company_id"), "website_checks", ["company_id"], unique=False
    )
    op.create_table(
        "company_contact_sources",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "contact_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["company_contacts.id"],
            name=op.f("fk_company_contact_sources_contact_id_company_contacts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company_contact_sources")),
        sa.UniqueConstraint(
            "contact_id", "source", name=op.f("uq_company_contact_sources_contact_id")
        ),
    )
    op.create_index(
        op.f("ix_company_contact_sources_contact_id"),
        "company_contact_sources",
        ["contact_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_company_contact_sources_contact_id"), table_name="company_contact_sources"
    )
    op.drop_table("company_contact_sources")
    op.drop_index(op.f("ix_website_checks_company_id"), table_name="website_checks")
    op.drop_index(op.f("ix_website_checks_checked_at"), table_name="website_checks")
    op.drop_table("website_checks")
    op.drop_index(op.f("ix_search_job_sources_search_job_id"), table_name="search_job_sources")
    op.drop_table("search_job_sources")
    op.drop_index(op.f("ix_search_job_companies_search_job_id"), table_name="search_job_companies")
    op.drop_index(op.f("ix_search_job_companies_company_id"), table_name="search_job_companies")
    op.drop_table("search_job_companies")
    op.drop_index(op.f("ix_job_outbox_search_job_id"), table_name="job_outbox")
    op.drop_index(op.f("ix_job_outbox_published_at"), table_name="job_outbox")
    op.drop_table("job_outbox")
    op.drop_index(op.f("ix_company_sources_company_id"), table_name="company_sources")
    op.drop_table("company_sources")
    op.drop_index(op.f("ix_company_contacts_type"), table_name="company_contacts")
    op.drop_index(op.f("ix_company_contacts_normalized_value"), table_name="company_contacts")
    op.drop_index(op.f("ix_company_contacts_company_id"), table_name="company_contacts")
    op.drop_table("company_contacts")
    op.drop_table("sheet_exports")
    op.drop_index(op.f("ix_search_jobs_status"), table_name="search_jobs")
    op.drop_table("search_jobs")
    op.drop_index(op.f("ix_companies_website_status"), table_name="companies")
    op.drop_index(op.f("ix_companies_site_opportunity_score"), table_name="companies")
    op.drop_index(op.f("ix_companies_registrable_domain"), table_name="companies")
    op.drop_index(op.f("ix_companies_primary_category"), table_name="companies")
    op.drop_index(op.f("ix_companies_normalized_name"), table_name="companies")
    op.drop_index(op.f("ix_companies_normalized_address"), table_name="companies")
    op.drop_index("ix_companies_name_address", table_name="companies")
    op.drop_index(op.f("ix_companies_lead_state"), table_name="companies")
    op.drop_index(op.f("ix_companies_contacts_found"), table_name="companies")
    op.drop_index(op.f("ix_companies_cms"), table_name="companies")
    op.drop_index("ix_companies_city_score", table_name="companies")
    op.drop_index(op.f("ix_companies_city"), table_name="companies")
    op.drop_table("companies")
    # ### end Alembic commands ###
